### ISSUE TITLE
fixed_start_coef setup

### ISSUE THREAD

**Issue by jonghunlee1** [larslau/progmod#1]
Hi, I am Jonghun Lee, Sr scientist at Takeda pharmaceuticals.
Thank you very much for sharing this great model with all the code.
I have a question regarding setting up the fixed_start_coef.
I am trying to modify your code to apply CDRSB, but the model keep failing to converge.
Could you please provide the fixed_start_coef set for CDRSB if you have?
Did you use the ADNIMERGE.csv for all the experiments or collected the relevant records by yourselves?

Thank you in advance!
Jonghun Lee

**Comment by larslau** [comment]
Hi Jonghun Lee. 

The current version is a bit sensitive to starting parameters (I will post an update at some point, but it will probably not be in the next few months). Typically, one can tweak starting parameters a bit and get the model to converge - sometimes it requires more work (e.g. fixing individual parameters and fitting the model for the other parameters, then starting from the new estimates). And sometimes the chosen model simply does not fit the data.

One place to start is to force the model to return an object even if it does not converge:
`control = nlmeControl(returnObject = TRUE)
That may give you some better estimates of starting parameters. 

If you continue to experience problems, please post your code and error messages - then I'll see what I can do.

**Comment by jonghunlee1** [comment]
Dear Raket,

Thank you very much for your fast response.
Your suggestion worked well so the model eventually converged.
I do appreciate for this great model!
Let me please re-contact after further modeling.

Best,
Jonghun Lee
